# Generated by Django 3.0.2 on 2020-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TEAM_Login',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('pass_word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TEAM_Register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('stu1_name', models.CharField(max_length=100)),
                ('stu2_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('pass_word', models.CharField(max_length=100)),
                ('conf_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
