# Generated by Django 3.0.2 on 2020-02-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tth2020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clues',
            fields=[
                ('clue_id', models.AutoField(primary_key=True, serialize=False)),
                ('clue_seq', models.CharField(max_length=10)),
                ('clue_pattern', models.CharField(max_length=10)),
                ('clue_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
