# Generated by Django 3.0.2 on 2020-02-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tth2020', '0002_clues'),
    ]

    operations = [
        migrations.AddField(
            model_name='clues',
            name='clue_ans',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
